name: 'Build and Push Docker Image to Artifactory'
description: 'GitHub Composite Action to Build and Push Docker Image to Artifactory'
inputs:
  registry-user:
    description: 'Registry User'
    required: true
  registry-password:
    description: 'Registry Password'
    required: true
  repository-name:
    description: 'Artifactory Virtual Repository name to upload package'
    required: true
  registry-url:
    description: 'Artifactory Virtual Repository name to upload package'
    required: true
  image-name:
    description: 'Docker Image Name'
    required: true
  image-tag:
    description: 'Docker Image Tag'
    required: true
  image-version:
    description: 'Docker Image Version'
    required: true
runs:
  using: "composite"
  steps:     
  - id: build-and-push
    run: |      
      #docker login https://cepsaregistry.jfrog.io/ui/repos/tree/General/${{ inputs.repository-name }} -u ${{ inputs.registry-user }} -p ${{ inputs.registry-password }}
      #docker login https://cepsa.jfrog.io/td-docker-local/${{ inputs.repository-name }} -u ${{ inputs.registry-user }} -p ${{ inputs.registry-password }}
      docker login https://cepsa.jfrog.io/api/docker/td-docker-local/ -u ${{ inputs.registry-user }} -p ${{ inputs.registry-password }}
      #docker build -t example .
      echo "build"
      docker build -t example . --tag ${{ inputs.image-tag }}
      echo imageid=$(docker images -q ${{ inputs.image-name }})
      #echo "tag"
      docker tag  example cepsa.jfrog.io/api/docker/td-docker-local/example:latest
      docker image ls
      echo "push"
      #docker push https://cepsa.jfrog.io/api/docker/${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-version }}
      #echo https://cepsa.jfrog.io/api/docker/${{ inputs.repository-name }}/${{ inputs.image-name }}:${{ inputs.image-version }}
      docker push cepsa.jfrog.io/api/docker/td-docker-local/example:0.1
    shell: bash
